# Copyright 2019-2023 David Robillard <d@drobilla.net>
# SPDX-License-Identifier: 0BSD OR GPL-3.0-or-later

stages: [build, deploy]

default:
  stage: build
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dwerror=true
    - ninja -C build test

dev:
  stage: build
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Db_coverage=true
    - ninja -C build test
    - ninja -C build coverage-html
    - meson configure -Dbuildtype=release -Db_coverage=false build
    - ninja -C build test
  coverage: '/ *lines\.*: \d+\.\d+.*/'
  artifacts:
    paths:
      - build/meson-logs/coveragereport

static:
  stage: build
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Ddefault_library=static -Dwarning_level=3 -Dwerror=true
    - ninja -C build test

sanitize:
  stage: build
  image: lv2plugin/debian-x64-clang
  script:
    - meson setup build -Db_lundef=false -Dbuildtype=plain -Dwarning_level=3 -Dwerror=true -Dcpp_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero" -Dcpp_link_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero"
    - ninja -C build test
    - meson configure build -Dbuildtype=debugoptimized -Dcpp_args="" -Dcpp_link_args=""
    - meson configure build -Db_sanitize=memory
    - ninja -C build test
  variables:
    CXX: "clang++"

# Linux distributions

fedora:
  stage: build
  image: lv2plugin/fedora-dev
  script:
    - meson setup build --wrap-mode=forcefallback -Dbuildtype=plain -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
  variables:
    CXXFLAGS: -O2 -D_FORTIFY_SOURCE=2

# Linux Platforms

arm32:
  stage: build
  image: lv2plugin/debian-arm32
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/arm-linux-gnueabihf.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

arm64:
  stage: build
  image: lv2plugin/debian-arm64
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/aarch64-linux-gnu.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

x32:
  stage: build
  image: lv2plugin/debian-x32
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/i686-linux-gnu.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

# Non-Linux/Docker rows (not hosted)

freebsd:
  stage: build
  tags: [freebsd,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

mac:
  stage: build
  tags: [macos]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

win:
  stage: build
  tags: [windows,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

pages:
  stage: deploy
  script:
    - mkdir -p .public
    - mv build/meson-logs/coveragereport/ .public/coverage
    - mv .public public
  needs:
    - dev
  artifacts:
    paths:
      - public
  only:
    - master
